name = "RandomJapaneseSentence"
uuid = "bd350fca-59ae-4c58-acd6-653209881553"
authors = ["Markus-Amano <markus.a.amano@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
